# .github/workflows/caller-workflow.yml
on: [push]

env:
  SOME_VAR: "Global"

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    outputs:
      build-and-verify: ${{ steps.set-output-defaults.outputs.build-and-verify }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "::set-output name=build-and-verify::${{ github.event.inputs.build-and-verify || 'true' }}"        
  call-reusable:
    #needs: [EnvSetup]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my_variable: "Hardcoded"
      #my_variable: ${{ env.SOME_VAR }}
      #my_variable: ${{needs.EnvSetup.outputs.build-and-verify}}
