on: [push]

jobs:
  Deploy-SIT:
    uses: ./.github/workflows/deploy.yml
    with:
      space: r1
  Deploy-PROD-P11:
    uses: ./.github/workflows/deploy.yml
    with:
      space: p11-dmz
  Deploy-PROD-S11:
    uses: ./.github/workflows/deploy.yml
    with:
      space: s11-dmz
