on:
  workflow_call:
    inputs:
      space:
        required: true
        type: string
env:
  CONFIG: |
    p11: 
      JOB_NAME: DEPLOY P11
    p11-dmz:
      JOB_NAME: DEPLOY P11 DMZ

jobs:
  Deploy:
    name: ${{ fromjson(CONFIG)[inputs.space]['job_name'] }}
    runs-on: ubuntu-latest
    steps:
    - name: Use the passed variable
      run: |
        echo "${{ fromjson(CONFIG)[inputs.space]['job_name'] }}"
