# .github/workflows/reusable-workflow.yml
on:
  workflow_call:
    inputs:
      space:
        required: true
        type: string

jobs:
  use-variable:
    runs-on: ubuntu-latest
    name: ${{ vars.config['p11-dmz'].job_name }}
    steps:
    - name: Use the passed variable
      run: echo "The API URL is true"
