# .github/workflows/reusable-workflow.yml
on:
  workflow_call:
    inputs:
      space:
        required: true
        type: string

jobs:
  use-variable:
    name: ${{ fromjson(vars.CONFIG)['p11-dmz'] }}
    runs-on: ubuntu-latest
    steps:
    - name: Use the passed variable
      run: echo "The API URL is true"
